# prefix used with rss download of xbrl files
file_prefix = 'xbrlrss'

[url]
# The public example provided by IANA
example = 'http://example.com'
# A simple HTTP request and response service by Kenneth Reitz
simple = 'https://httpbin.org'
# EDGAR archives url
edgar = 'https://www.sec.gov/Archives/edgar'
# EDGAR monthly url
edgar_month = 'https://www.sec.gov/Archives/edgar/monthly'
# this is the old edgar monthly url.  It has http instead of https
# it can be used, for example, to test the http code 301
edgar_month_old = 'http://www.sec.gov/Archives/edgar/monthly'

[file]
rss202001 = 'xbrlrss-2020-01.xml'
rss202101 = 'xbrlrss-2021-01.xml'
